version: '3.3'
services:
  nginx:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=site1.com
      - LETSENCRYPT_HOST=site1.com
      - LETSENCRYPT_EMAIL=suphavit.b@itp.co.th
    volumes:                     
      - .:/etc/nginx/conf.d
networks:
  default:
    external:
      name: web